### ISSUE TITLE
tools directory and sunxi-tools

### ISSUE THREAD

**Issue by Vogtinator** [apritzel/pine64#11]
This repo contains some useful scripts and tools in the tools/ subdirectory.
Wouldn't it be better to add them to the linux-sunxi/sunxi-tools repository instead?

**Comment by apritzel** [comment]
Possibly, but actually this tool is becoming obsolete. I an in the process of upstreaming SPL support for U-Boot, so we don't need boot0 (or libdram) anymore, and everything is proper Open Source.
http://lists.denx.de/pipermail/u-boot/2016-November/273344.html
