### ISSUE TITLE
Defconfigs?

### ISSUE THREAD

**Issue by g40** [apritzel/pine64#14]
Hello @apritzel 

Thanks for this. Invaluable assistance. 

The readme [https://github.com/apritzel/pine64/blob/master/binaries/README.md](url) mentions defconfig files for the DDR setup binaries

i.e. `sun50i-h5-ddr3-spl_defconfig`. Where are these located?

TAIA.

**Comment by apritzel** [comment]
They are in [this U-Boot repository](https://github.com/apritzel/u-boot/commits/sunxi64-fel32). I have a new version ready, which simplifies things and has a higher change of going upstream. Will post it in a few days.

**Comment by g40** [comment]
That sounds very promising. Thanks for both.
